spring:
  application:
    name: detector
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: detector
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

server:
  port: 8081

watchdog:
  kafka:
    metrics-topic: metrics
    deploys-topic: deploys
    alerts-topic: alerts

management:
  endpoints:
    web:
      exposure:
        include: health, info
